### ISSUE TITLE
Download files with createRemoteFileNode

### ISSUE THREAD

**Issue by KyleAMathews** [DanielOliver/gatsby-source-azure-storage#1]
Noticed your cool plugin today! Thought you might be interested in the `createRemoteFileNode` helper function which does a lot of nice things for you around downloading remote files and such.

https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=source-filesyste#createremotefilenode

**Comment by DanielOliver** [comment]
Hey, that's a good call-out.  I don't know if I can use the remote file download directly easily, but it might  be worth me looking at at least making a node entry there to match.  RIght now I'm using  [getBlobToLocalFile](http://azure.github.io/azure-storage-node/BlobService.html#getBlobToLocalFile__anchor)

**Comment by KyleAMathews** [comment]
Ah so you can't get the actual remote URL?

**Comment by DanielOliver** [comment]
I know I can, there's a [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api)  and the [SDK has a method for it](http://azure.github.io/azure-storage-node/BlobService.html#getUrl__anchor).  But I'd rather stick with the SDK download methods if I can.

**Comment by KyleAMathews** [comment]
Sure, the only reason to opt-in to this is that then you're remote files are made into File nodes automatically meaning they are available for transformation e.g. with gatsby-plugin-sharp and use with gatsby-image.

**Comment by DanielOliver** [comment]
Ahhhhhh, that is good to know.  My particular use-case does involve downloading images from Azure blobs.  I'll need to look into getting those into the file nodes.

**Comment by DanielOliver** [comment]
Thanks for the info Kyle! I've added this by using gatsby-source-filesystem as a dependency for the create file node method.  I also then added the "url" as an extra property because so far as any other plugin knows, each file from this plugin is local.
